repos:
  - repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
    rev: v4.1.0
    hooks:
      - id: commitlint
        stages: [commit-msg]
        additional_dependencies: ["@commitlint/config-conventional"]

  - repo: local
    hooks:
      - id: markdownlint
        name: markdownlint
        files: \.md$
        entry: markdownlint
        language: node
        stages: [commit]
        args: ["--ignore", "**/target/**/*.md"]

  - repo: https://github.com/golangci/golangci-lint
    rev: v1.41.1 # the current latest version
    hooks:
      - id: golangci-lint
